### PR TITLE
Assign correct InputFilter to Post of RpcService

### LINKED ISSUE #81: Cannot create RPC-Service because of wrong InputFilter
### Bug Report

With v1.10.3, it is not possible to create a new service, as the wrong filter is taken for the POST action;

image

|    Q        |   A
|------------ | ------
| Version(s)  | 1.10.3

#### Current behavior

You cannot add a RPC-Service with the "New Service" Button. You receive an 422 error instead:

```
detail: "Failed Validation"
status: 422
title: "Unprocessable Entity"
type: "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html"
validation_messages: {controller_class: ["The Controller Class must be a valid, fully qualified, PHP class name"],…}
accept_whitelist: ["The Accept Whitelist must be an array of valid media type expressions"]
content_type_whitelist: ["The Content-Type Whitelist must be an array of valid media type expressions"]
controller_class: ["The Controller Class must be a valid, fully qualified, PHP class name"]
http_methods: ["The HTTP Methods must be an array of valid HTTP method names"] 
```

#### How to reproduce

- Setup a new app (here's my composer.json; I'm using PHP 8.0)
``` {
    "require": {
        "php": "^7.3 || ~8.0.0",
        "laminas-api-tools/api-tools": "^1.5",
        "laminas-api-tools/api-tools-documentation": "^1.3",
        "laminas-api-tools/api-tools-rpc": "^1.6",
        "laminas/laminas-component-installer": "^2.1.1",
        "laminas/laminas-development-mode": "^3.2",
        "laminas/laminas-i18n": "^2.13",
        "laminas/laminas-zendframework-bridge": "^1.0"
    },
    "require-dev": {
        "laminas-api-tools/api-tools-admin": "^1.6",
        "laminas-api-tools/api-tools-asset-manager": "^1.2",
        "laminas/laminas-coding-standard": "~2.3.0",
        "laminas/laminas-composer-autoloading": "^2.1",
        "laminas/laminas-developer-tools": "^2.0",
        "laminas/laminas-test": "^4.0",
        "phpunit/phpunit": "^9.5",
        "roave/security-advisories": "dev-master"
    },
    "conflict": {
        "laminas/laminas-hydrator": "<2.0",
        "laminas/laminas-stdlib": "<3.2.1",
        "laminas/laminas-view": "<2.10.1"
    },
    "suggest": {
        "laminas-api-tools/api-tools-doctrine": "laminas-api-tools/api-tools-doctrine ^2.2 to create Doctrine-Connected REST services",
        "laminas-api-tools/api-tools-http-cache": "laminas-api-tools/api-tools-http-cache ^1.4 to add HTTP caching to your API",
        "zfr/zfr-cors": "zfr/zfr-cors ^1.5 to add CORS support to your API"
    },
 ```
- Press "New Service"
- Select the scope
- Enter any name and route
- Press "Create Service"
- You got the 422 Error

#### Expected behavior

- Adding the RPC should work
- The POST-method is validated against the RpcPostInputFilter instead of the RpcPatchInputFilter

### PR DESCRIPTION
**Pull request by calvarezm70**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
Assign correct InputFilter to Post of RpcService

Fix bug 
**Cannot create RPC-Service because of wrong InputFilter** #81

### CODE REVIEW

**Comment by froschdesign** [comment]
@calvarezm70 
Please use for bug fixes the current stable release branch: [2.0.x](https://github.com/laminas-api-tools/api-tools-admin/tree/2.0.x)

See [contributing guidelines](https://github.com/laminas-api-tools/.github/blob/5b3e0cb814531070652af6715feb817f266f5b20/CONTRIBUTING.md) for reference:

> #### What branch to issue the pull request against?
> 
> Which branch should you issue a pull request against?
> 
> - For fixes against the stable release, issue the pull request against the release branch matching the minor release you want to fix.
> - For new features, or fixes that introduce new elements to the public API (such as new public methods or properties), issue the pull request against the default branch.

https://github.com/laminas-api-tools/.github/blob/5b3e0cb814531070652af6715feb817f266f5b20/CONTRIBUTING.md#what-branch-to-issue-the-pull-request-against

Thanks in advance! 👍

**Comment by Ocramius** [comment]
Indeed, one commit to be rebased out :)

**Comment by calvarezm70** [comment]
@froschdesign 

Sorry for the mistake and thanks for the information.

**Comment by RoelVoordendag** [comment]
Is there any progress on this MR? It would be a great benefit to merge this :)

**Comment by tasmaniski** [comment]
sorry to bother you, this problem happens at the very beginning of use Laminas API tools, 
it would be great if we have this merged.

**Comment by Xerkus** [comment]
First introduced in 1.10.2 via https://github.com/laminas-api-tools/api-tools-admin/commit/19f4a9565292a0a594df4aff842f3583bf61a668#diff-9d8a0efd4da10600e826531479ee3b004713024b25fa385882beb27ca496f6f0R1797a

**Pull request merged**
