### PR TITLE
#75 bugfix in Rest Service PATCH parameter validation

### LINKED ISSUE #75: Impossible to save Rest Service in 1.10.2 - Problem with page size parameter
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.10.2

#### Summary

After upgrading from 1.9.0 to 1.10.2, I can no longer save the General Settings of a REST Service.

#### Current behavior

The PATCH request to `/api-tools/api/module/tms/rest/tms-V1-Rest-xxxxxxxxxx-Controller` fails with a 422 error, saying:
```
page_size: ["The Page Size must be either a positive integer or the value "-1" (disabling pagination)"]
```
The related fields from the request body are:
```
page_size: "50"
page_size_param: null
```
When switching back to 1.9.0, the problem disappears.

### PR DESCRIPTION
**Pull request by ppaulis**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This fixes the bug described in #75 .

The concerned part is:
```
if (is_numeric($value) && intval($value) !== $value) {
    return false;
}
```
This validation makes no sense the way it is, because the Webinterface sends strings like "50", and in this case `intval($value) !== $value` always evaluates to true, due to the strict comparison. Instead, the validation should be :
```
if (!is_numeric($value) || intval($value) != $value) {
    return false;
}
```
as proposed in this PR.

### CODE REVIEW

**Comment by ppaulis** [comment]
@weierophinney The 1.11.x seems to have the same problem. Do you want me to do the same PR for 1.11.x?

**Comment by froschdesign** [comment]
@ppaulis 
This change needs a test case which illustrates the problem.

> The 1.11.x seems to have the same problem. Do you want me to do the same PR for 1.11.x?

Not necessary, if this bugfix is accepted and merged then it will also be included in the 1.11.x branch.

**Comment by ppaulis** [comment]
@froschdesign Hi and thanks for the quick reply!

There is indeed a unit test, but it's wrong :

**Comment by ppaulis** [comment]
hi @froschdesign  and thanks for the quick reply!
There is indeed already a unit test but it's wrong:
https://github.com/laminas-api-tools/api-tools-admin/blob/1406d72b84938937d2cf6aa09a24437f40856381/test/InputFilter/RestService/PatchInputFilterTest.php#L58

The line should be :
```
'page_size'                  => "25",
```

I'll fix the test.

**Comment by ppaulis** [comment]
@froschdesign there are a few problems with my signoff in the commits. I'll close this PR and reopen a new proper one.

**Comment by weierophinney** [comment]
@ppaulis You don't need to close! [Our contributor documentation details how to add sign-off after the fact](https://github.com/laminas/.github/blob/main/CONTRIBUTING.md#adding-signoffs-after-the-fact) - it's basically a rebase with a flag to add sign-off, plus a force push back to your branch. Go ahead and re-open, and follow the documentation, and we can then review.

**Comment by ppaulis** [comment]
@weierophinney thanks! Should have read that before -.-
There's already a new one that has more progress : #77

**Pull request closed without merging**
