### PR TITLE
Allow PHP 8.1 and remove deprecated `/api/package` feature

### PR DESCRIPTION
**Pull request by snapshotpl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Allow install on PHP 8.1

### CODE REVIEW

**Comment by snapshotpl** [comment]
Fails on `zfcampus/zf-deploy` dependency, but it's abandoned. Any suggestion?

**Comment by Ocramius** [comment]
I see it's in `require-dev`: can we kill it?

**Comment by snapshotpl** [comment]
Not sure. Looks like it's needed to build packages (optional feature), but I have never use it.
@ezimuel @weierophinney

**Comment by weierophinney** [comment]
The admin includes a tab for creating a deployment package from your application - that's why the dependency exists here. We'd need to drop that tab from the UI package before dropping it here.

**Comment by Ocramius** [comment]
@snapshotpl there's now a PHP 8.1-compatible release of `laminas-api-tools/api-tools` 👍

**Review by Ocramius — APPROVED** [review]
LGTM - let's :ship: this. I'll release `2.0.0` with this

**Comment by Ocramius** [comment]
Released `2.0.0`, thanks @snapshotpl!

**Pull request merged**
